name: Keep Backend Awake

# Cronjob: alle 15 Minuten
on:
  schedule:
    - cron: "0 16 * * 2" # every tuesday at 16
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Ping backend
        run: |
          echo "Pinging Backend..."
          response=$(curl -i -X GET https://countries-backend-zm89.onrender.com/test)
          echo "HTTP Response: $response"
          if [[ $response == *"200"* ]]; then
            echo "✓ Backend is awake"
          else
            echo "✗ Backend ping failed"
          fi
