name: Keep Supabase Awake

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase
        run: |
          echo "Pinging Supabase..."
          supabase_response=$(curl -s -o /dev/null -w "%{http_code}" \
            "https://xwrxnjvxaqourbysahes.supabase.co/rest/v1/health" \
            -H "apikey: $SUPABASE_ANON_KEY")

          echo "Supabase HTTP: $supabase_response"

          if [ "$supabase_response" == "200" ]; then
            echo "✓ Supabase is awake"
          else
            echo "✗ Supabase ping failed (HTTP $supabase_response)"
          fi
