name: Keep Backend Awake

# Cronjob: alle 15 Minuten
on:
  schedule:
    - cron: "0 16 * * 2" # every tuesday at 16
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Ping backend
        run: |
          echo "Pinging Backend..."
          response=$(curl -s -w "%{http_code}" -o /dev/null https://countries-backend.onrender.com/ping)
          echo "HTTP Response: $response"
